### ISSUE TITLE
爬虫失效

### ISSUE THREAD

**Issue by childrentime** [SmacUL/NewsRecommend#6]
楼主，爬虫失效了，求一份填了数据的sql文件😚

**Comment by swimrabbit-jy** [comment]
你做出来了吗？新闻推荐系统

**Comment by twelveli** [comment]
> 你做出来了吗？新闻推荐系统

请问你做出来了吗？

**Comment by baodongshu123** [comment]
> 楼主，爬虫失效了，求一份填了数据的sql文件😚

您好，请问您有完整数据的sql文件吗，我复现的时候爬虫功能也用不了

**Comment by childrentime** [comment]
太久远了，以前做出来了。不过现在肯定找不到文件了🥲

**Comment by baodongshu123** [comment]
好吧，还是感谢感谢大佬回信




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmacUL/NewsRecommend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 下午5:25
***@***.***&gt;;
抄送:&nbsp;"Dongshu ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmacUL/NewsRecommend] 爬虫失效 (Issue #6)





 
太久远了，以前做出来了。不过现在肯定找不到文件了🥲
